source "https://rubygems.org"

gem 'jekyll'
# gem 'rake'
# gem 'pry'
# gem 'rdiscount'
# gem 'pygments.rb'
# gem 'RedCloth'
# gem 'haml'
# gem 'compass'
# gem 'sass'
# gem 'sass-globbing'
# gem 'rubypants'
# gem 'rb-fsevent'
# gem 'stringex'
# gem 'liquid'
# gem 'directory_watcher'
gem 'kramdown'
gem 'jekyll-paginate'
# gem 'coderay'
# gem 'sinatra'
